### ISSUE TITLE
polkit enabled?

### ISSUE THREAD

**Issue by techie2000** [s1n7ax/nixos#1]
Hi.
First off, this is not an issue (necessarily) but you don't have 'discussions' enabled where ordinarily I would have raised this.

I am investing many nixos config projects as I prepare my own exploration/implementation of nixos.

I see you have a polkit rule under `security.polkit.extraConfig` in [system/core/polkit.nix](https://github.com/s1n7ax/nixos/blob/main/system/core/polkit.nix) which is called in a couple of profiles.

However, I'm wondering whether this will work without setting `security.polkit.enable = true;` (the default value being `false` [security.polkit.enable](https://search.nixos.org/options?channel=24.05&show=security.polkit.enable&from=0&size=50&sort=relevance&type=packages&query=polkit) )? Or does the implementation of a rule enable it dynamically/lazily?

**Comment by s1n7ax** [comment]
@techie2000 Polkit is being enabled by `services.udisks2.enable = true;`.
https://github.com/NixOS/nixpkgs/blob/8c50662509100d53229d4be607f1a3a31157fa12/nixos/modules/services/hardware/udisks2.nix#L85

**Comment by techie2000** [comment]
ah, I see. I hadn't delved in to the core nix implementation. Thankyou for clarifying. I think I will explicitly enable it to avoid forgetting this information down the line 😄
